### ISSUE TITLE
Separate Events by region

### ISSUE THREAD

**Issue by iggirex** [askadev/askadev.org#12]
It would be easier if the list of events was separated by geographical region (probably not enough events yet to do by country). This would help people find events more quickly.

**Comment by tshedor** [comment]
@iggirex do you mean region by, say, continent? There's an suggestive search above the list of events, but perhaps the UI needs to call more attention to it.

**Comment by iggirex** [comment]
Oh wow you're right! Yep didn't even see that lolz, yea maybe it can be a little more apparent that that feature is there.

**Comment by iggirex** [comment]
@tshedor yep, that catches the eye more effectively

**Comment by tshedor** [comment]
Grand, closing this out.
